spring:

  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/metrodb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 250
      maximum-pool-size: 50


  jpa:
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 15
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        query:
          plan_cache_max_size: 4096
          in_clause_parameter_padding: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



app:
  jwt-secret: asd-dfz-h1702-aasx2701-f40nt-7ayd1
  jwt-refresh-secret: f2401-sad-adf-f2401-f5sf-ae9-4272-bc78-as-y3kd1
  jwt-expiration: 7200
  jwt-refresh-expiration: 1000